### ISSUE TITLE
Drive API Abuse?

### ISSUE THREAD

**Issue by jof** [datacorruption/massif#2]
https://github.com/datacorruption/massif/blob/a3c4134ef73e414782cefbe27a7a8065c07deb65/massif.py#L217

Aren't you worried about strangers messing with your spreadsheet?

This project is splendid, and I'd hate to see it go defunct.

One alternative approach could be to periodically save the sheet into a CSV that can live in the repo.

**Comment by datacorruption** [comment]
The service account specified in client_secret.json only has read access to the spreadsheet. That being said, there may be other potential concerns around this implementation so I'll leave this issue open for discussion.

**Comment by jffng** [comment]
Huge fan of this project.

Perhaps creating a sheety API out of the existing google sheet data store is a quick and dirty way to go: https://sheety.co/
